// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCLfZWEYLbBBkQzCnyEq02myw0HhSzBc',
    appId: '1:81637060365:web:0d1a332b045bb847994a44',
    messagingSenderId: '81637060365',
    projectId: 'studdybussyapp',
    authDomain: 'studdybussyapp.firebaseapp.com',
    storageBucket: 'studdybussyapp.appspot.com',
    measurementId: 'G-840GSC2E9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUutiuIkWiOAZLjeFt0LKi0Vv1N6Q67ik',
    appId: '1:81637060365:android:78337234a9794ad2994a44',
    messagingSenderId: '81637060365',
    projectId: 'studdybussyapp',
    storageBucket: 'studdybussyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEfMRszDn6sdNdOyDQMEZvue2bo9AA54',
    appId: '1:81637060365:ios:87c439af213f84db994a44',
    messagingSenderId: '81637060365',
    projectId: 'studdybussyapp',
    storageBucket: 'studdybussyapp.appspot.com',
    iosBundleId: 'com.example.studybuddyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEfMRszDn6sdNdOyDQMEZvue2bo9AA54',
    appId: '1:81637060365:ios:41e9d534ed4bfaff994a44',
    messagingSenderId: '81637060365',
    projectId: 'studdybussyapp',
    storageBucket: 'studdybussyapp.appspot.com',
    iosBundleId: 'com.example.studybuddyapp.RunnerTests',
  );
}
